apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: set-time
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: set-time
            image: registry.hub.docker.com/vchilikov/kube_proba
            command: ["python", "set_time.py"]
            env:
            - name: REDIS_HOST
              value: redis
          restartPolicy: OnFailure
